version: '3.8'

services:
  node:
    container_name: redspher-calculator-node
    tty: true
    build:
      context: ./node
    volumes:
      - ./app:/var/www/symfony_docker
  php:
    container_name: redspher-calculator-php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
  nginx:
    container_name: redspher-calculator-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
